In [1]:
import pandas as pd
import numpy as np

In [2]:
# DataFrame cơ cấu ngành
df_industry = pd.read_excel('Philippine-ICB.xlsx')

In [3]:
df_industry

,Name,Symbol,RIC,Type,NAME,COMPANY NAME,ICB INDUSTRY NAME
0,SM INVESTMENTS,PH:SNV,SM.PS,PH:SNV,SM INVESTMENTS,SM INVESTMENTS CORP,Consumer Discretionary
1,SM PRIME HOLDINGS,PH:SMP,SMPH.PS,PH:SMP,SM PRIME HOLDINGS,"SM PRIME HOLDINGS, INC.",Real Estate
2,AYALA,PH:ACA,AC.PS,PH:ACA,AYALA,AYALA CORPORATION,Real Estate
3,BDO UNIBANK,PH:BDO,BDO.PS,PH:BDO,BDO UNIBANK,BDO UNIBANK INCORPORATED,Financials
4,JOLLIBEE FOODS,PH:JFC,JFC.PS,PH:JFC,JOLLIBEE FOODS,JOLLIBEE FOODS CORPORATION,Consumer Discretionary
...,...,...,...,...,...,...,...
576,THE ENERGY CORP. 'B',PH:ECO,-,PH:ECO,THE ENERGY CORP. 'B' DEAD - DELIST.27/02/97,NaN,Basic Materials
577,UEM DEV. PHILS 'B',51801N,-,51801N,UEM DEV. PHILS 'B',SYNERGY GRID & DEVELOPMENT PHILS INC,Industrials
578,UNIOIL & GAS DEV.'B',PH:UOB,-,PH:UOB,UNIOIL & GAS DEV.'B' DEAD - MERGER 503328,NaN,Financials
579,WISE HOLDINGS 'B',PH:DPB,WHIB.PS^C11,PH:DPB,WISE HOLDINGS 'B' DEAD - DELIST.10/03/11,WISE HOLDINGS INCORPORATED,Financials
580,ATLAS CONS.MNG.'B',PH:ATB,-,PH:ATB,ATLAS CONS.MNG.'B' DEAD - MERGER 998177,ATLAS CONSOLIDATED MINING AND DEVELOPMENT CORP,Basic Materials

In [4]:
df_industry = df_industry.drop(['RIC','COMPANY NAME','NAME'],axis=1)

In [5]:
df_industry

                     Name  Symbol    Type       ICB INDUSTRY NAME
0          SM INVESTMENTS  PH:SNV  PH:SNV  Consumer Discretionary
1       SM PRIME HOLDINGS  PH:SMP  PH:SMP             Real Estate
2                   AYALA  PH:ACA  PH:ACA             Real Estate
3             BDO UNIBANK  PH:BDO  PH:BDO              Financials
4          JOLLIBEE FOODS  PH:JFC  PH:JFC  Consumer Discretionary
..                    ...     ...     ...                     ...
576  THE ENERGY CORP. 'B'  PH:ECO  PH:ECO         Basic Materials
577    UEM DEV. PHILS 'B'  51801N  51801N             Industrials
578  UNIOIL & GAS DEV.'B'  PH:UOB  PH:UOB              Financials
579     WISE HOLDINGS 'B'  PH:DPB  PH:DPB              Financials
580    ATLAS CONS.MNG.'B'  PH:ATB  PH:ATB         Basic Materials

[581 rows x 4 columns]

In [6]:
industry = list(df_industry['ICB INDUSTRY NAME'])
symbol = df_industry['Symbol']
name = list(df_industry['Name'])

File dữ liệu Stock

In [7]:
df = pd.ExcelFile('Philippine-Price-Market-Cap.xlsx')
# Đọc sheet 1
df_1 = pd.read_excel(df,'Price',index_col=0,parse_dates=True)
# Đọc sheet 2
df_2 = pd.read_excel(df,'Market Cap',index_col=0,parse_dates=True)

In [8]:
# Sheet1 transportation
price_sheet = df_1.T

price_sheet.insert(0, "Industry", industry)

price_sheet = price_sheet.T

# Sheet2 transportation
marketcap_sheet = df_2.T

marketcap_sheet.insert(0, "Industry", industry)

marketcap_sheet = marketcap_sheet.T

In [9]:
# Viết hàm xóa bỏ các ngành Error

def delete_error(df):
    for i in df.columns:
        if 'ERROR' in i:
            df = df.drop(i,axis=1)
    return df

price_sheet = delete_error(price_sheet)
marketcap_sheet = delete_error(marketcap_sheet)

In [10]:
# Kiểm tra dữ liệu NaN
print(price_sheet.iloc[0].isnull().sum())

print(marketcap_sheet.iloc[0].isnull().sum())

1
1

In [11]:
# Xóa dữ liệu NaN trong ngành sheet 1
x = np.where(price_sheet.iloc[0].isnull())

price_sheet = price_sheet.drop(price_sheet.columns[x], axis=1) 

# Xóa dữ liệu NaN trong ngành sheet 2
y = np.where(marketcap_sheet.iloc[0].isnull())

marketcap_sheet = marketcap_sheet.drop(marketcap_sheet.columns[y], axis=1)

In [12]:
# Kiểm tra dữ liệu NaN
print(price_sheet.iloc[0].isnull().sum())

print(marketcap_sheet.iloc[0].isnull().sum())

0
0

In [13]:
# Phương thức xóa dữ liệu NaN của giá cổ phiếu
def drop_columns_with_na(df):
    for i in df.columns:
        if df[i].isnull().any():
            df=df.drop(i,axis=1)
    return df

price_sheet = drop_columns_with_na(price_sheet)

marketcap_sheet = drop_columns_with_na(marketcap_sheet)



print('Tổng missing data sheet 1:',price_sheet.isnull().sum().sum())
print('Tổng missing data sheet 2:',marketcap_sheet.isnull().sum().sum())

Tổng missing data sheet 1: 0
Tổng missing data sheet 2: 0

In [14]:
# Xuất file đã clean data
price_sheet.to_excel("data_cleaned_final_sheet_1.xlsx")
marketcap_sheet.to_excel("data_cleaned_final_sheet_2.xlsx")